Repository ISPP-G10/flatter, pull requests merged in 2023-03, with the labels that each got.

#98 Task/082
  backend/backend/schema.py
  backend/backend/settings/development.py
  backend/mainApp/models.py
  backend/mainApp/mutations.py
  backend/mainApp/queries.py
  backend/mainApp/types.py
Labels: enhancement, backend, grupo 2

#92 Task/050
  client/src/App.js
  client/src/components/slideShow.js
  client/src/components/smallProfile.js
  client/src/pages/detalleVivienda.js
  client/src/static/css/components/slideShow.css
  client/src/static/css/components/smallProfile.css
  client/src/static/css/detalleVivienda.css
  client/src/static/files/icons/chat.png
  client/src/static/files/icons/estrella.png
  client/src/static/files/icons/usuario.png
  client/src/static/files/images/estudiante1.jpeg
  client/src/static/files/images/estudiante2.jpeg
  client/src/static/files/images/propietario.jpeg
Labels: enhancement, frontend, grupo 1

#116 FEAT: Property tagging
  backend/backend/schema.py
  backend/mainApp/mutations.py
  backend/mainApp/queries.py
  backend/mainApp/types.py
Labels: enhancement

#100 Task/085
  client/package.json
  client/src/App.js
  client/src/components/BtnSlider.js
  client/src/components/Slider.js
  client/src/components/icons/left-arrow.svg
  client/src/components/icons/right-arrow.svg
  client/src/pages/searchProperties.js
  client/src/static/css/components/Slider.css
  client/src/static/css/searchProperties.css
  client/yarn.lock
Labels: frontend, grupo 2

#106 Task/075
  client/package.json
  client/src/App.js
  client/src/components/formBuilder.js
  client/src/components/formProperty.js
  client/src/components/modalProperty.js
  client/src/pages/landingPage.js
  client/src/pages/propertyPage.js
  client/src/sections/flatterPage.js
  client/src/sections/imageUploader.js
  client/src/sections/modal.js
  client/src/sections/solidButton.js
  client/src/static/css/globals.css
  client/src/static/css/ownerProperties.css
  client/src/static/css/pages/landing.css
  client/src/static/css/pages/property.css
  client/src/static/css/sections/button.css
  client/src/static/css/sections/imageUploader.css
  client/src/static/css/sections/modal.css
  client/yarn.lock
Labels: enhancement, frontend, grupo 2

#163 FEAT: DATOS USUARIOS PILOTOS
  backend/authentication/fixtures/testers.json
  backend/mainApp/fixtures/properties.json
Labels: backend, grupo 1, grupo 2

#207 FIX: ARREGLA CLASES FOOTER
  client/src/sections/footer.js
Labels: bug, frontend, grupo 1, sprint 2

#208 FEAT: EDITAR PROPIEDAD EN DETALLES
  client/src/api/propertiesAPI.js
  client/src/pages/propertyDetails.js
Labels: enhancement, frontend, grupo 1, sprint 2

#240 FEAT: DISEÑO PISOS FAVORITOS
  client/src/App.js
  client/src/pages/accountSettings.js
  client/src/pages/favouritesProperties.js
  client/src/static/css/sections/button.css
Labels: enhancement, frontend, grupo 1, sprint 2

#244 FIX: solución al error de creación al editar propiedades
  client/src/components/forms/formProperty.js
Labels: bug, frontend

#245 Task/181
  client/src/App.js
  client/src/components/forms/formInput.js
  client/src/forms/filterRequestsForm.js
  client/src/libs/validators/filterRequestsValidators.js
  client/src/pages/listProperties.js
  client/src/pages/propertyRequests.js
  client/src/sections/solidButton.js
  client/src/static/css/pages/listProperties.css
  client/src/static/css/pages/propertyRequests.css
Labels: enhancement, frontend, grupo 2, sprint 2

#252 Task/251
  client/src/api/propertiesAPI.js
  client/src/pages/listProperties.js
  client/src/pages/propertyRequests.js
Labels: bug, frontend, integration, grupo 2, sprint 2

#267 Task/195
  backend/mainApp/fixtures/properties.json
  backend/mainApp/mutations.py
  backend/mainApp/queries.py
  client/src/api/propertiesAPI.js
  client/src/components/property/favouriteButton.js
  client/src/pages/favouritesProperties.js
  client/src/pages/propertyDetails.js
  client/src/static/css/components/favouriteButton.css
  client/src/static/css/pages/propertyDetails.css
Labels: enhancement, frontend, backend, grupo 1, sprint 2

#270 Task/264
  backend/mainApp/mutations.py
  backend/mainApp/queries.py
  client/src/api/propertiesAPI.js
  client/src/forms/propertyRequestsInputs.js
  client/src/pages/listProperties.js
  client/src/pages/propertyDetails.js
  client/src/static/css/pages/propertyDetails.css
Labels: frontend, integration, grupo 2, sprint 2
