Repository ISPP-G10/flatter, pull requests merged in 2023-04, with the labels that each got.

#356 FEAT: COMPRA DE FC Y CESTA
  client/src/App.js
  client/src/components/shop/shopCesta.js
  client/src/components/shop/shopOption.js
  client/src/pages/accountSettings.js
  client/src/pages/shopPage.js
  client/src/static/css/components/shopCesta.css
  client/src/static/css/components/shopOption.css
  client/src/static/css/pages/shopPage.css
Labels: design, frontend, grupo 1, sprint 3

#352 Diseño página de planes de pago
  client/package.json
  client/src/App.js
  client/src/components/pricingOption.js
  client/src/pages/accountSettings.js
  client/src/pages/pricingPage.js
  client/src/static/css/components/pricingOption.css
  client/src/static/css/pages/pricingPage.css
  client/yarn.lock
Labels: design, frontend, grupo 1, sprint 3

#372 Destacar con FlatterCoins
  backend/authentication/mutations.py
  backend/mainApp/mutations.py
  backend/mainApp/tests.py
  client/src/pages/ownerProperties.js
Labels: frontend, backend, grupo 1, sprint 3

#386 BUG: INTERVAL EN LOS FILTROS
  client/src/pages/listProperties.js
Labels: enhancement, frontend, integration, grupo 2

#384 FEATURE: BADGE DE FAVORITOS Y DISTINTIVO EN PISOS DESTACADOS
  backend/media/properties/images/prohscq.png
  client/src/pages/listProperties.js
  client/src/pages/ownerProperties.js
  client/src/static/css/pages/listProperties.css
  client/src/static/css/pages/ownerProperties.css
Labels: enhancement, frontend, integration, grupo 2

#385 FEATURE: INTEGRACIÓN PAGINACIÓN EN LISTADO DE PROPIEDADES Y BÚSQUEDA DE USUARIOS
  backend/authentication/queries.py
  backend/authentication/types.py
  backend/mainApp/queries.py
  backend/mainApp/tests.py
  backend/mainApp/types.py
  client/src/api/propertiesAPI.js
  client/src/api/usersAPI.js
  client/src/components/pagination.js
  client/src/pages/listProperties.js
  client/src/pages/searchUsers.js
  client/src/static/css/components/pagination.css
Labels: enhancement, frontend, integration, grupo 2
